# Utiliser l'image PHP officielle
FROM php:8.0-fpm

# Installer les extensions nécessaires et Composer
RUN apt-get update && apt-get install -y \
    libzip-dev \
    && docker-php-ext-install zip \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Définir le répertoire de travail
WORKDIR /var/www

# Copier le contenu du projet
COPY . .

# Installer les dépendances
RUN composer install --no-dev --optimize-autoloader

# Exposer le port
EXPOSE 9000

# Démarrer le serveur
CMD ["php-fpm"]
